import React, { ReactNode } from 'react';
import {
  SiPlaywright,
  SiNvidia,
  SiCplusplus,
  SiIntellijidea,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiMongodb,
  SiElasticsearch,
  SiRedux,
  SiStorybook,
  SiVuedotjs,
  SiAngular,
  SiGraphql,
  SiDocker,
  SiAmazonaws,
  SiPostgresql,
  SiMysql,
  SiPython,
  SiRust,
  SiHtml5,
  SiCss3,
  SiSass,
  SiWebpack,
  SiFigma,
  SiGit,
  SiGithub,
  SiFirebase,
  SiTailwindcss,
  SiExpress,
  SiNestjs,
  SiVercel,
  SiNetlify,
  SiLinux,
  SiJest,
  SiPrisma,
  SiStripe,
  SiWordpress,
  SiPhp,
  SiSwift,
  SiKotlin,
  SiFlutter,
  SiDjango,
  SiFlask,
  SiRuby,
  SiGo,
  SiSvelte,
  SiVite,
  SiApollographql,
  SiSocketdotio,
  SiRedis,
  SiNginx,
  SiTensorflow,
  SiPytorch,
  SiKeras,
  SiJupyter,
  SiNumpy,
  SiPandas,
  SiScikitlearn,
  SiOpencv,
  SiOpenai,
  SiKaggle,
  SiMlflow,
  SiSpacy,
  SiOnnx,
  SiApacheairflow,
  SiApachespark,
  SiApachehadoop,
  SiApachekafka,
  SiApachehive,
  SiDatabricks,
  SiSnowflake,
  SiTableau,
  SiPowerbi,
  SiBootstrap,
  SiJquery,
  SiGatsby,
  SiNuxtdotjs,
  SiElectron,
  SiThreedotjs,
  SiD3Dotjs,
  SiGitlab,
  SiBitbucket,
  SiJenkins,
  SiJira,
  SiGooglecloud,
  SiMicrosoftazure,
  SiKubernetes,
  SiTerraform,
  SiAnsible,
  SiArduino,
  SiRaspberrypi,
  SiFramer,
  SiChakraui,
  SiAntdesign,
  SiBabel,
  SiPrettier,
  SiEslint,
  SiRemix,
  SiAstro,
  SiIonic,
  SiCapacitor,
  SiTauri,
  SiPwa,
  SiWebassembly,
  SiEmberdotjs,
  SiSupabase,
  SiPlanetscale,
  SiApachecassandra,
  SiAmazondynamodb,
  SiApachecouchdb,
  SiMariadb,
  SiSqlite,
  SiInfluxdb,
  SiFastapi,
  SiStreamlit,
  SiRay,
  SiWeightsandbiases,
  SiReactquery,
  SiPlotly,
  SiPolars,
  SiDuckdb,
  SiMicrosoftexcel,
  SiGoogleanalytics,
  SiLooker,
  SiRadixui,
  SiAuth0,
  SiWebrtc,
  SiHelm,
  SiArgo,
  SiPrometheus,
  SiGrafana,
  SiIstio,
  SiEnvoyproxy,
  SiVault,
  SiCircleci,
  SiGithubactions,
  SiPulumi,
  SiK3S,
  SiRedhatopenshift,
  SiRancher,
  SiKnative,
  SiContainerd,
  SiLeetcode,
  SiCodechef,
  SiCodeforces,
  SiHackerrank,
  SiGeeksforgeeks,
  SiPycharm,
  SiYolo,
} from 'react-icons/si';

export interface TechIconOption {
  name: string;
  label: string;
  component: ReactNode;
}

export const TECH_ICONS: TechIconOption[] = [
  { name: 'SiJavascript', label: 'JavaScript', component: <img src="https://cdn.simpleicons.org/javascript" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="javascript" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiTypescript', label: 'TypeScript', component: <img src="https://cdn.simpleicons.org/typescript" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="typescript" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiReact', label: 'React', component: <img src="https://cdn.simpleicons.org/react" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="react" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiNextdotjs', label: 'Next.js', component: <img src="https://cdn.simpleicons.org/nextdotjs/white" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="nextdotjs/white" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiNodedotjs', label: 'Node.js', component: <img src="https://cdn.simpleicons.org/nodedotjs" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="nodedotjs" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiMongodb', label: 'MongoDB', component: <img src="https://cdn.simpleicons.org/mongodb" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="mongodb" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiElasticsearch', label: 'Elasticsearch', component: <img src="https://cdn.simpleicons.org/elasticsearch" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="elasticsearch" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiRedux', label: 'Redux', component: <img src="https://cdn.simpleicons.org/redux" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="redux" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiStorybook', label: 'Storybook', component: <img src="https://cdn.simpleicons.org/storybook" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="storybook" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiVuedotjs', label: 'Vue.js', component: <img src="https://cdn.simpleicons.org/vuedotjs" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="vuedotjs" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiAngular', label: 'Angular', component: <img src="https://cdn.simpleicons.org/angular" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="angular" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiGraphql', label: 'GraphQL', component: <img src="https://cdn.simpleicons.org/graphql" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="graphql" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiDocker', label: 'Docker', component: <img src="https://cdn.simpleicons.org/docker" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="docker" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiAmazonaws', label: 'AWS', component: <img src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/amazonwebservices/amazonwebservices-original-wordmark.svg" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="amazonaws" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiPostgresql', label: 'PostgreSQL', component: <img src="https://cdn.simpleicons.org/postgresql" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="postgresql" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiMysql', label: 'MySQL', component: <img src="https://cdn.simpleicons.org/mysql" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="mysql" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiPython', label: 'Python', component: <img src="https://cdn.simpleicons.org/python" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="python" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiRust', label: 'Rust', component: <img src="https://cdn.simpleicons.org/rust" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="rust" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiHtml5', label: 'HTML5', component: <SiHtml5 /> },
  { name: 'SiCss3', label: 'CSS3', component: <SiCss3 /> },
  { name: 'SiSass', label: 'Sass', component: <img src="https://cdn.simpleicons.org/sass" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="sass" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiWebpack', label: 'Webpack', component: <img src="https://cdn.simpleicons.org/webpack" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="webpack" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiFigma', label: 'Figma', component: <img src="https://cdn.simpleicons.org/figma" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="figma" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiGit', label: 'Git', component: <img src="https://cdn.simpleicons.org/git" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="git" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiGithub', label: 'GitHub', component: <img src="https://cdn.simpleicons.org/github/white" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="github/white" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiFirebase', label: 'Firebase', component: <img src="https://cdn.simpleicons.org/firebase" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="firebase" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiTailwindcss', label: 'Tailwind CSS', component: <img src="https://cdn.simpleicons.org/tailwindcss" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="tailwindcss" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiExpress', label: 'Express', component: <img src="https://cdn.simpleicons.org/express" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="express" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiNestjs', label: 'NestJS', component: <img src="https://cdn.simpleicons.org/nestjs" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="nestjs" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiVercel', label: 'Vercel', component: <img src="https://cdn.simpleicons.org/vercel/white" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="vercel/white" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiNetlify', label: 'Netlify', component: <img src="https://cdn.simpleicons.org/netlify" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="netlify" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiLinux', label: 'Linux', component: <img src="https://cdn.simpleicons.org/linux" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="linux" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiJest', label: 'Jest', component: <img src="https://cdn.simpleicons.org/jest" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="jest" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiPrisma', label: 'Prisma', component: <img src="https://cdn.simpleicons.org/prisma/white" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="prisma/white" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiStripe', label: 'Stripe', component: <img src="https://cdn.simpleicons.org/stripe" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="stripe" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiWordpress', label: 'WordPress', component: <img src="https://cdn.simpleicons.org/wordpress" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="wordpress" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiPhp', label: 'PHP', component: <img src="https://cdn.simpleicons.org/php" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="php" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiSwift', label: 'Swift', component: <img src="https://cdn.simpleicons.org/swift" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="swift" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiKotlin', label: 'Kotlin', component: <img src="https://cdn.simpleicons.org/kotlin" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="kotlin" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiFlutter', label: 'Flutter', component: <img src="https://cdn.simpleicons.org/flutter" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="flutter" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiDjango', label: 'Django', component: <img src="https://cdn.simpleicons.org/django" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="django" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiFlask', label: 'Flask', component: <img src="https://cdn.simpleicons.org/flask" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="flask" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiRuby', label: 'Ruby', component: <img src="https://cdn.simpleicons.org/ruby" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="ruby" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiGo', label: 'Go', component: <img src="https://cdn.simpleicons.org/go" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="go" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiSvelte', label: 'Svelte', component: <img src="https://cdn.simpleicons.org/svelte" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="svelte" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiVite', label: 'Vite', component: <img src="https://cdn.simpleicons.org/vite" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="vite" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiApollographql', label: 'Apollo GraphQL', component: <img src="https://cdn.simpleicons.org/apollographql" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="apollographql" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiSocketdotio', label: 'Socket.io', component: <img src="https://cdn.simpleicons.org/socketdotio/white" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="socketdotio/white" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiRedis', label: 'Redis', component: <img src="https://cdn.simpleicons.org/redis" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="redis" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiNginx', label: 'Nginx', component: <img src="https://cdn.simpleicons.org/nginx" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="nginx" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiTensorflow', label: 'TensorFlow', component: <img src="https://cdn.simpleicons.org/tensorflow" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="tensorflow" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiPytorch', label: 'PyTorch', component: <img src="https://cdn.simpleicons.org/pytorch" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="pytorch" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiKeras', label: 'Keras', component: <img src="https://cdn.simpleicons.org/keras" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="keras" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiJupyter', label: 'Jupyter', component: <img src="https://cdn.simpleicons.org/jupyter" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="jupyter" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiNumpy', label: 'NumPy', component: <img src="https://cdn.simpleicons.org/numpy" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="numpy" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiPandas', label: 'Pandas', component: <img src="https://cdn.simpleicons.org/pandas" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="pandas" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiScikitlearn', label: 'scikit-learn', component: <img src="https://cdn.simpleicons.org/scikitlearn" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="scikitlearn" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiOpencv', label: 'OpenCV', component: <img src="https://cdn.simpleicons.org/opencv" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="opencv" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiOpenai', label: 'OpenAI', component: <img src="https://cdn.simpleicons.org/openai" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="openai" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiKaggle', label: 'Kaggle', component: <img src="https://cdn.simpleicons.org/kaggle" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="kaggle" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiMlflow', label: 'MLflow', component: <img src="https://cdn.simpleicons.org/mlflow" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="mlflow" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiSpacy', label: 'spaCy', component: <img src="https://cdn.simpleicons.org/spacy" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="spacy" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiOnnx', label: 'ONNX', component: <img src="https://cdn.simpleicons.org/onnx" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="onnx" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiApacheairflow', label: 'Apache Airflow', component: <img src="https://cdn.simpleicons.org/apacheairflow" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="apacheairflow" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiApachespark', label: 'Apache Spark', component: <img src="https://cdn.simpleicons.org/apachespark" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="apachespark" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiApachehadoop', label: 'Apache Hadoop', component: <img src="https://cdn.simpleicons.org/apachehadoop" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="apachehadoop" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiApachekafka', label: 'Apache Kafka', component: <img src="https://cdn.simpleicons.org/apachekafka" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="apachekafka" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiApachehive', label: 'Apache Hive', component: <img src="https://cdn.simpleicons.org/apachehive" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="apachehive" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiDatabricks', label: 'Databricks', component: <img src="https://cdn.simpleicons.org/databricks" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="databricks" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiSnowflake', label: 'Snowflake', component: <img src="https://cdn.simpleicons.org/snowflake" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="snowflake" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiTableau', label: 'Tableau', component: <img src="https://cdn.simpleicons.org/tableau" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="tableau" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiPowerbi', label: 'Power BI', component: <img src="https://cdn.simpleicons.org/powerbi" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="powerbi" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiBootstrap', label: 'Bootstrap', component: <img src="https://cdn.simpleicons.org/bootstrap" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="bootstrap" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiJquery', label: 'jQuery', component: <img src="https://cdn.simpleicons.org/jquery" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="jquery" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiGatsby', label: 'Gatsby', component: <img src="https://cdn.simpleicons.org/gatsby" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="gatsby" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiNuxtdotjs', label: 'Nuxt.js', component: <img src="https://cdn.simpleicons.org/nuxtdotjs" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="nuxtdotjs" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiElectron', label: 'Electron', component: <img src="https://cdn.simpleicons.org/electron" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="electron" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiThreedotjs', label: 'Three.js', component: <img src="https://cdn.simpleicons.org/threedotjs" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="threedotjs" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiD3Dotjs', label: 'D3.js', component: <SiD3Dotjs /> },
  { name: 'SiGitlab', label: 'GitLab', component: <img src="https://cdn.simpleicons.org/gitlab" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="gitlab" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiBitbucket', label: 'Bitbucket', component: <img src="https://cdn.simpleicons.org/bitbucket" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="bitbucket" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiJenkins', label: 'Jenkins', component: <img src="https://cdn.simpleicons.org/jenkins" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="jenkins" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiJira', label: 'Jira', component: <img src="https://cdn.simpleicons.org/jira" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="jira" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiGooglecloud', label: 'Google Cloud', component: <img src="https://cdn.simpleicons.org/googlecloud" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="googlecloud" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiMicrosoftazure', label: 'Microsoft Azure', component: <img src="https://cdn.simpleicons.org/microsoftazure" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="microsoftazure" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiKubernetes', label: 'Kubernetes', component: <img src="https://cdn.simpleicons.org/kubernetes" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="kubernetes" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiTerraform', label: 'Terraform', component: <img src="https://cdn.simpleicons.org/terraform" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="terraform" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiAnsible', label: 'Ansible', component: <img src="https://cdn.simpleicons.org/ansible" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="ansible" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiArduino', label: 'Arduino', component: <img src="https://cdn.simpleicons.org/arduino" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="arduino" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiRaspberrypi', label: 'Raspberry Pi', component: <img src="https://cdn.simpleicons.org/raspberrypi" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="raspberrypi" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiFramer', label: 'Framer', component: <img src="https://cdn.simpleicons.org/framer" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="framer" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiChakraui', label: 'Chakra UI', component: <img src="https://cdn.simpleicons.org/chakraui" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="chakraui" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiAntdesign', label: 'Ant Design', component: <img src="https://cdn.simpleicons.org/antdesign" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="antdesign" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiBabel', label: 'Babel', component: <img src="https://cdn.simpleicons.org/babel" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="babel" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiPrettier', label: 'Prettier', component: <img src="https://cdn.simpleicons.org/prettier" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="prettier" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiEslint', label: 'ESLint', component: <img src="https://cdn.simpleicons.org/eslint" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="eslint" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiRemix', label: 'Remix', component: <img src="https://cdn.simpleicons.org/remix" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="remix" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiAstro', label: 'Astro', component: <img src="https://cdn.simpleicons.org/astro" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="astro" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiIonic', label: 'Ionic', component: <img src="https://cdn.simpleicons.org/ionic" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="ionic" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiCapacitor', label: 'Capacitor', component: <img src="https://cdn.simpleicons.org/capacitor" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="capacitor" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiTauri', label: 'Tauri', component: <img src="https://cdn.simpleicons.org/tauri" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="tauri" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiPwa', label: 'PWA', component: <img src="https://cdn.simpleicons.org/pwa" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="pwa" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiWebassembly', label: 'WebAssembly', component: <img src="https://cdn.simpleicons.org/webassembly" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="webassembly" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiEmberdotjs', label: 'Ember.js', component: <img src="https://cdn.simpleicons.org/emberdotjs" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="emberdotjs" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiSupabase', label: 'Supabase', component: <img src="https://cdn.simpleicons.org/supabase" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="supabase" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiPlanetscale', label: 'PlanetScale', component: <img src="https://cdn.simpleicons.org/planetscale" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="planetscale" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiApachecassandra', label: 'Cassandra', component: <img src="https://cdn.simpleicons.org/apachecassandra" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="apachecassandra" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiAmazondynamodb', label: 'DynamoDB', component: <img src="https://cdn.simpleicons.org/amazondynamodb" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="amazondynamodb" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiApachecouchdb', label: 'CouchDB', component: <img src="https://cdn.simpleicons.org/apachecouchdb" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="apachecouchdb" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiMariadb', label: 'MariaDB', component: <img src="https://cdn.simpleicons.org/mariadb" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="mariadb" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiSqlite', label: 'SQLite', component: <img src="https://cdn.simpleicons.org/sqlite" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="sqlite" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiInfluxdb', label: 'InfluxDB', component: <img src="https://cdn.simpleicons.org/influxdb" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="influxdb" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiFastapi', label: 'FastAPI', component: <img src="https://cdn.simpleicons.org/fastapi" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="fastapi" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiStreamlit', label: 'Streamlit', component: <img src="https://cdn.simpleicons.org/streamlit" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="streamlit" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiRay', label: 'Ray', component: <img src="https://cdn.simpleicons.org/ray" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="ray" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiWeightsandbiases', label: 'Weights & Biases', component: <img src="https://cdn.simpleicons.org/weightsandbiases" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="weightsandbiases" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiReactquery', label: 'TanStack Query', component: <img src="https://cdn.simpleicons.org/reactquery" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="reactquery" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiPlotly', label: 'Plotly', component: <img src="https://cdn.simpleicons.org/plotly" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="plotly" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiPolars', label: 'Polars', component: <img src="https://cdn.simpleicons.org/polars" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="polars" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiDuckdb', label: 'DuckDB', component: <img src="https://cdn.simpleicons.org/duckdb" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="duckdb" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiMicrosoftexcel', label: 'Excel', component: <img src="https://cdn.simpleicons.org/microsoftexcel" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="microsoftexcel" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiGoogleanalytics', label: 'Google Analytics', component: <img src="https://cdn.simpleicons.org/googleanalytics" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="googleanalytics" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiLooker', label: 'Looker', component: <img src="https://cdn.simpleicons.org/looker" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="looker" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiRadixui', label: 'Radix UI', component: <img src="https://cdn.simpleicons.org/radixui" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="radixui" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiAuth0', label: 'Auth0', component: <SiAuth0 /> },
  { name: 'SiWebrtc', label: 'WebRTC', component: <img src="https://cdn.simpleicons.org/webrtc" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="webrtc" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiHelm', label: 'Helm', component: <img src="https://cdn.simpleicons.org/helm" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="helm" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiArgo', label: 'ArgoCD', component: <img src="https://cdn.simpleicons.org/argo" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="argo" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiPrometheus', label: 'Prometheus', component: <img src="https://cdn.simpleicons.org/prometheus" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="prometheus" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiGrafana', label: 'Grafana', component: <img src="https://cdn.simpleicons.org/grafana" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="grafana" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiIstio', label: 'Istio', component: <img src="https://cdn.simpleicons.org/istio" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="istio" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiEnvoyproxy', label: 'Envoy', component: <img src="https://cdn.simpleicons.org/envoyproxy" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="envoyproxy" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiVault', label: 'Vault', component: <img src="https://cdn.simpleicons.org/vault" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="vault" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiCircleci', label: 'CircleCI', component: <img src="https://cdn.simpleicons.org/circleci" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="circleci" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiGithubactions', label: 'GitHub Actions', component: <img src="https://cdn.simpleicons.org/githubactions" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="githubactions" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiPulumi', label: 'Pulumi', component: <img src="https://cdn.simpleicons.org/pulumi" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="pulumi" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiK3S', label: 'K3s', component: <SiK3S /> },
  { name: 'SiRedhatopenshift', label: 'OpenShift', component: <img src="https://cdn.simpleicons.org/redhatopenshift" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="redhatopenshift" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiRancher', label: 'Rancher', component: <img src="https://cdn.simpleicons.org/rancher" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="rancher" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiKnative', label: 'Knative', component: <img src="https://cdn.simpleicons.org/knative" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="knative" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiContainerd', label: 'Containerd', component: <img src="https://cdn.simpleicons.org/containerd" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="containerd" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiLeetcode', label: 'LeetCode', component: <img src="https://cdn.simpleicons.org/leetcode" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="leetcode" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiCodechef', label: 'CodeChef', component: <img src="https://cdn.simpleicons.org/codechef" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="codechef" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiCodeforces', label: 'Codeforces', component: <img src="https://cdn.simpleicons.org/codeforces" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="codeforces" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiHackerrank', label: 'HackerRank', component: <img src="https://cdn.simpleicons.org/hackerrank" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="hackerrank" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiGeeksforgeeks', label: 'GeeksForGeeks', component: <img src="https://cdn.simpleicons.org/geeksforgeeks" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="geeksforgeeks" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiPycharm', label: 'PyCharm', component: <img src="https://cdn.simpleicons.org/pycharm" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="pycharm" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SiYolo', label: 'YOLO', component: <img src="https://cdn.simpleicons.org/yolo" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="yolo" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'HuggingFace', label: 'Hugging Face', component: <img src="https://cdn.simpleicons.org/huggingface/FFD21E" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Hugging Face" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'LangChain', label: 'LangChain', component: <img src="https://cdn.simpleicons.org/langchain/1C3C3C" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="LangChain" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'LangGraph', label: 'LangGraph', component: <img src="https://cdn.simpleicons.org/langchain/2E8B57" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="LangGraph" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'LlamaIndex', label: 'LlamaIndex', component: <img src="https://cdn.simpleicons.org/meta/0081FB" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="LlamaIndex" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Gradio', label: 'Gradio', component: <img src="https://cdn.simpleicons.org/gradio/FF7C00" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Gradio" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'DeepSpeed', label: 'DeepSpeed', component: <img src="https://cdn.simpleicons.org/pytorch/EE4C2C" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="DeepSpeed" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'AutoGluon', label: 'AutoGluon', component: <img src="https://cdn.simpleicons.org/scikitlearn/F7931E" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="AutoGluon" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Matplotlib', label: 'Matplotlib', component: <svg viewBox="0 0 24 24" width="1em" height="1em" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 19h16M4 15l4-6 4 2 4-5 4 4" /></svg> },
  { name: 'Seaborn', label: 'Seaborn', component: <img src="https://cdn.simpleicons.org/scikitlearn/3776AB" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Seaborn" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'ApacheSuperset', label: 'Apache Superset', component: <img src="https://cdn.simpleicons.org/apachesuperset/20A7C9" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Apache Superset" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'NeonDB', label: 'Neon', component: <img src="https://cdn.simpleicons.org/postgresql/316192" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Neon" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Zustand', label: 'Zustand', component: <img src="https://cdn.simpleicons.org/redux/764ABC" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Zustand" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'ShadcnUI', label: 'ShadCN UI', component: <img src="https://cdn.simpleicons.org/shadcnui/000000" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="ShadCN UI" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Clerk', label: 'Clerk', component: <img src="https://cdn.simpleicons.org/clerk/6C47FF" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Clerk" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SupabaseAuth', label: 'Supabase Auth', component: <img src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/supabase/supabase-original.svg" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Supabase Auth" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  // C / C++
  { name: 'C', label: 'C', component: <img src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/c/c-original.svg" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="C" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'CPlusPlus', label: 'C++', component: <img src="https://cdn.simpleicons.org/cplusplus" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="cplusplus" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'CMake', label: 'CMake', component: <img src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/cmake/cmake-original.svg" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="CMake" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Qt', label: 'Qt', component: <img src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/qt/qt-original.svg" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Qt" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'OpenGL', label: 'OpenGL', component: <img src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/opengl/opengl-original.svg" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="OpenGL" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'CUDA', label: 'CUDA', component: <img src="https://cdn.simpleicons.org/nvidia" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="nvidia" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'GDB', label: 'GDB', component: <img src="https://cdn.simpleicons.org/gnu/A42E2B" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="GDB" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  // Java
  { name: 'Java', label: 'Java', component: <img src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/java/java-original.svg" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Java" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SpringBoot', label: 'Spring Boot', component: <img src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/spring/spring-original.svg" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Spring Boot" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Maven', label: 'Maven', component: <img src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/maven/maven-original.svg" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Maven" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Gradle', label: 'Gradle', component: <img src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/gradle/gradle-original.svg" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Gradle" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Hibernate', label: 'Hibernate', component: <img src="https://cdn.simpleicons.org/hibernate/59666C" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Hibernate" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'JUnit', label: 'JUnit', component: <img src="https://cdn.simpleicons.org/junit5/25A162" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="JUnit" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Tomcat', label: 'Tomcat', component: <img src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tomcat/tomcat-original.svg" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Tomcat" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'IntelliJIDEA', label: 'IntelliJ IDEA', component: <img src="https://cdn.simpleicons.org/intellijidea" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="intellijidea" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  // JavaScript packages
  { name: 'Lodash', label: 'Lodash', component: <img src="https://cdn.simpleicons.org/lodash/3492FF" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Lodash" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Axios', label: 'Axios', component: <img src="https://cdn.simpleicons.org/axios/5A29E4" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Axios" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Momentjs', label: 'Moment.js', component: <svg viewBox="0 0 24 24" width="1em" height="1em" fill="currentColor"><path d="M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8z"/><path d="M12.5 7H11v6l5.25 3.15.75-1.23-4.5-2.67z"/></svg> },
  { name: 'Chartjs', label: 'Chart.js', component: <img src="https://cdn.simpleicons.org/chartdotjs/FF6384" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Chart.js" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'RxJS', label: 'RxJS', component: <img src="https://cdn.simpleicons.org/reactivex/B7178C" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="RxJS" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Vitest', label: 'Vitest', component: <img src="https://cdn.simpleicons.org/vitest/6E9F18" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Vitest" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Cypress', label: 'Cypress', component: <img src="https://cdn.simpleicons.org/cypress/17202C" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Cypress" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Playwright', label: 'Playwright', component: <img src="https://cdn.simpleicons.org/playwright" style={{ width: '1em', height: '1em', objectFit: 'contain', display: 'inline-block' }} alt="playwright" onError={(e) => { e.currentTarget.src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Zod', label: 'Zod', component: <img src="https://cdn.simpleicons.org/zod/3E67B1" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Zod" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'pnpm', label: 'pnpm', component: <img src="https://cdn.simpleicons.org/pnpm/F69220" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="pnpm" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Yarn', label: 'Yarn', component: <img src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/yarn/yarn-original.svg" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Yarn" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Rollup', label: 'Rollup', component: <img src="https://cdn.simpleicons.org/rollupdotjs/EC4A3F" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Rollup" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'MobX', label: 'MobX', component: <img src="https://cdn.simpleicons.org/mobx/FF7102" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="MobX" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Turborepo', label: 'Turborepo', component: <img src="https://cdn.simpleicons.org/turborepo/EF4444" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Turborepo" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  // Python packages
  { name: 'SciPy', label: 'SciPy', component: <img src="https://cdn.simpleicons.org/scipy/8CAAE6" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="SciPy" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Celery', label: 'Celery', component: <img src="https://cdn.simpleicons.org/celery/37814A" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Celery" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'SQLAlchemy', label: 'SQLAlchemy', component: <img src="https://cdn.simpleicons.org/sqlalchemy/D71F00" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="SQLAlchemy" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Scrapy', label: 'Scrapy', component: <img src="https://cdn.simpleicons.org/scrapy/60A839" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Scrapy" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'pytest', label: 'pytest', component: <img src="https://cdn.simpleicons.org/pytest/0A9EDC" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="pytest" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Poetry', label: 'Poetry', component: <img src="https://cdn.simpleicons.org/poetry/60A5FA" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Poetry" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Pydantic', label: 'Pydantic', component: <img src="https://cdn.simpleicons.org/pydantic/E92063" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Pydantic" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Anaconda', label: 'Anaconda', component: <img src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/anaconda/anaconda-original.svg" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Anaconda" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'pip', label: 'pip', component: <img src="https://cdn.simpleicons.org/pypi/3775A9" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="pip" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
  { name: 'Uvicorn', label: 'Uvicorn', component: <img src="https://cdn.simpleicons.org/fastapi/009688" style={{ width: '1em', height: '1em', objectFit: 'contain' as const, display: 'inline-block' }} alt="Uvicorn" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/assets/portfolio/skills/check.svg"; }} /> },
];

export function getIconByName(name: string): ReactNode | null {
  const found = TECH_ICONS.find((icon) => icon.name === name);
  return found ? found.component : null;
}

export function renderTechIcons(names: string[]): ReactNode[] {
  return names.map((name, i) => {
    const found = TECH_ICONS.find((icon) => icon.name === name);
    if (!found) return null;
    return React.cloneElement(found.component as React.ReactElement, {
      key: i,
      className: 'tech-icon',
    });
  }).filter(Boolean) as ReactNode[];
}
